import { Inter,Roboto } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const roboto = Roboto({ weight:['900'], subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App DVA',
  description: 'Generated by Developer',
}

export default function RootLayout({ children,...res }) {
  console.log('RootLayout', res)
  return (
    <html lang="en">
      <body className={roboto.className}>
        <h1>HEADER</h1>
        <hr/>
        {children}
        <hr/>
        <h1>FOOOTER</h1>
      </body>
    </html>
  )
}
